codecov:
  require_ci_to_pass: true
  branch: master
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false
    project:
      default: false
      backend:
        target: 80%
        flags:
          - namexapi
          - colinapi
          - namexpay
      ui:
        target: 35%
        flags:
          - authweb

ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  namexapi:
    paths:
      - api/namex
    carryforward: true
  colinapi:
    paths:
      - colin-api/app
    carryforward: true
  namexpay:
    paths:
      - services/namex-pay/src/namex-pay
    carryforward: true
