name: Auto Analyze CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "services/auto-analyze/**"

jobs:
  auto-analyze-ci:
    env:
      DATABASE_TEST_USERNAME: postgres
      DATABASE_TEST_PASSWORD: postgres
      DATABASE_TEST_NAME: postgres
      DATABASE_TEST_HOST: localhost
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: postgres

    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./services/auto-analyze

    if: github.repository == 'bcgov/namex'

    strategy:
      matrix:
        python-version: [3.8]

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make setup
      - name: Lint with pylint
        run: |
          make pylint
        continue-on-error: true
      - name: Lint with flake8
        run: |
          make flake8
        continue-on-error: true
      - name: Test with pytest
        run: |
          make test
        continue-on-error: true
      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    file: ./services/auto-analyze/coverage.xml
      #    flags: autoanalyze
      #    name: codecov-auto-analyze
      #    fail_ci_if_error: true
      - name: build to check strictness
        run: |
          make build-nc
